class Autogenerated {
  String? firstname;
  String? lastname;
  String? username;
  String? password;
  String? email;

  Autogenerated(
      {this.firstname,
      this.lastname,
      this.username,
      this.password,
      this.email});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    firstname = json['firstname'];
    lastname = json['lastname'];
    username = json['username'];
    password = json['password'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['firstname'] = this.firstname;
    data['lastname'] = this.lastname;
    data['username'] = this.username;
    data['password'] = this.password;
    data['email'] = this.email;
    return data;
  }
}